// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mshtgnehxxbjoybwjagt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zaHRnbmVoeHhiam95YndqYWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzcwMzgsImV4cCI6MjA2Mzc1MzAzOH0.T9rM3ueECK8dPdQHJDLjS3vd2lsSZ5M_9JuP0Jq5VWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);