// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhvdzapwvquzabtuvllp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodmR6YXB3dnF1emFidHV2bGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTk4OTUsImV4cCI6MjA2MzY3NTg5NX0.r713Il6mEDz9VIujO2vDw9Yw-hHx9J61MG1xwtQL_Oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);